repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        types: [python]
    -   id: ruff
        name: ruff
        entry: ruff check --no-cache
        language: python
        types: [python]
